# Generated by Django 3.2.5 on 2021-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210717_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
